import torch
import torch.nn as nn
import torch.nn.functional as F

class MobileNetV2(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()

        self.conv1 = nn.Conv2d(3, 27, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        self.bn1 = nn.BatchNorm2d(27, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv1 = nn.Conv2d(27, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn1 = nn.BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv2 = nn.Conv2d(24, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=24, bias=False)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn2 = nn.BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv3 = nn.Conv2d(24, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn3 = nn.BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv1 = nn.Conv2d(16, 72, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn1 = nn.BatchNorm2d(72, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv2 = nn.Conv2d(72, 72, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=72, bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn2 = nn.BatchNorm2d(72, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv3 = nn.Conv2d(72, 10, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn3 = nn.BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv1 = nn.Conv2d(10, 100, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn1 = nn.BatchNorm2d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv2 = nn.Conv2d(100, 100, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=100, bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn2 = nn.BatchNorm2d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv3 = nn.Conv2d(100, 10, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn3 = nn.BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv1 = nn.Conv2d(10, 105, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn1 = nn.BatchNorm2d(105, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv2 = nn.Conv2d(105, 105, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=105, bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn2 = nn.BatchNorm2d(105, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv3 = nn.Conv2d(105, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn3 = nn.BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv1 = nn.Conv2d(24, 132, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn1 = nn.BatchNorm2d(132, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv2 = nn.Conv2d(132, 132, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=132, bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn2 = nn.BatchNorm2d(132, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv3 = nn.Conv2d(132, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn3 = nn.BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv1 = nn.Conv2d(24, 142, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn1 = nn.BatchNorm2d(142, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv2 = nn.Conv2d(142, 142, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=142, bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn2 = nn.BatchNorm2d(142, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv3 = nn.Conv2d(142, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn3 = nn.BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv1 = nn.Conv2d(24, 136, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn1 = nn.BatchNorm2d(136, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv2 = nn.Conv2d(136, 136, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=136, bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn2 = nn.BatchNorm2d(136, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv3 = nn.Conv2d(136, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn3 = nn.BatchNorm2d(31, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv1 = nn.Conv2d(31, 280, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn1 = nn.BatchNorm2d(280, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv2 = nn.Conv2d(280, 280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=280, bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn2 = nn.BatchNorm2d(280, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv3 = nn.Conv2d(280, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn3 = nn.BatchNorm2d(31, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv1 = nn.Conv2d(31, 262, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn1 = nn.BatchNorm2d(262, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv2 = nn.Conv2d(262, 262, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=262, bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn2 = nn.BatchNorm2d(262, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv3 = nn.Conv2d(262, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn3 = nn.BatchNorm2d(31, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv1 = nn.Conv2d(31, 278, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn1 = nn.BatchNorm2d(278, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv2 = nn.Conv2d(278, 278, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=278, bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn2 = nn.BatchNorm2d(278, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv3 = nn.Conv2d(278, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn3 = nn.BatchNorm2d(31, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv1 = nn.Conv2d(31, 270, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn1 = nn.BatchNorm2d(270, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv2 = nn.Conv2d(270, 270, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=270, bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn2 = nn.BatchNorm2d(270, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv3 = nn.Conv2d(270, 53, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn3 = nn.BatchNorm2d(53, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv1 = nn.Conv2d(53, 412, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn1 = nn.BatchNorm2d(412, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv2 = nn.Conv2d(412, 412, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=412, bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn2 = nn.BatchNorm2d(412, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv3 = nn.Conv2d(412, 53, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn3 = nn.BatchNorm2d(53, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv1 = nn.Conv2d(53, 430, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn1 = nn.BatchNorm2d(430, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv2 = nn.Conv2d(430, 430, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=430, bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn2 = nn.BatchNorm2d(430, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv3 = nn.Conv2d(430, 53, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn3 = nn.BatchNorm2d(53, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv1 = nn.Conv2d(53, 416, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn1 = nn.BatchNorm2d(416, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv2 = nn.Conv2d(416, 416, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=416, bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn2 = nn.BatchNorm2d(416, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv3 = nn.Conv2d(416, 108, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn3 = nn.BatchNorm2d(108, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv1 = nn.Conv2d(108, 687, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn1 = nn.BatchNorm2d(687, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv2 = nn.Conv2d(687, 687, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=687, bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn2 = nn.BatchNorm2d(687, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv3 = nn.Conv2d(687, 108, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn3 = nn.BatchNorm2d(108, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv1 = nn.Conv2d(108, 669, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn1 = nn.BatchNorm2d(669, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv2 = nn.Conv2d(669, 669, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=669, bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn2 = nn.BatchNorm2d(669, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv3 = nn.Conv2d(669, 108, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn3 = nn.BatchNorm2d(108, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv1 = nn.Conv2d(108, 686, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn1 = nn.BatchNorm2d(686, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv2 = nn.Conv2d(686, 686, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=686, bias=False)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn2 = nn.BatchNorm2d(686, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv3 = nn.Conv2d(686, 267, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn3 = nn.BatchNorm2d(267, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.conv_last = nn.Conv2d(267, 1110, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bn_last = nn.BatchNorm2d(1110, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.avgpool = nn.AdaptiveAvgPool2d(output_size=1)
        self.fc = nn.Linear(in_features=1110, out_features=1000, bias=True)

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn3(x)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn3(x)
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn3(x)
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn3(x)
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn3(x)
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn3(x)
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn3(x)
        x = self.conv_last(x)
        x = self.bn_last(x)
        x = F.relu6(x, inplace=True)
        x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

def mobilenetv2(**kwargs):
    return MobileNetV2(**kwargs)
