import torch
import torch.nn as nn
import torch.nn.functional as F

class MobileNetV2(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()

        self.conv1 = nn.Conv2d(3, 13, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        self.bn1 = nn.BatchNorm2d(13, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv1 = nn.Conv2d(13, 9, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn1 = nn.BatchNorm2d(9, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv2 = nn.Conv2d(9, 9, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=9, bias=False)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn2 = nn.BatchNorm2d(9, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv3 = nn.Conv2d(9, 8, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn3 = nn.BatchNorm2d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv1 = nn.Conv2d(8, 30, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn1 = nn.BatchNorm2d(30, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv2 = nn.Conv2d(30, 30, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=30, bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn2 = nn.BatchNorm2d(30, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv3 = nn.Conv2d(30, 8, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn3 = nn.BatchNorm2d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv1 = nn.Conv2d(8, 40, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn1 = nn.BatchNorm2d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv2 = nn.Conv2d(40, 40, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=40, bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn2 = nn.BatchNorm2d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv3 = nn.Conv2d(40, 8, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn3 = nn.BatchNorm2d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv1 = nn.Conv2d(8, 44, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn1 = nn.BatchNorm2d(44, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv2 = nn.Conv2d(44, 44, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=44, bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn2 = nn.BatchNorm2d(44, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv3 = nn.Conv2d(44, 10, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn3 = nn.BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv1 = nn.Conv2d(10, 66, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn1 = nn.BatchNorm2d(66, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv2 = nn.Conv2d(66, 66, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=66, bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn2 = nn.BatchNorm2d(66, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv3 = nn.Conv2d(66, 10, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn3 = nn.BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv1 = nn.Conv2d(10, 56, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn1 = nn.BatchNorm2d(56, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv2 = nn.Conv2d(56, 56, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=56, bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn2 = nn.BatchNorm2d(56, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv3 = nn.Conv2d(56, 10, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn3 = nn.BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv1 = nn.Conv2d(10, 52, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn1 = nn.BatchNorm2d(52, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv2 = nn.Conv2d(52, 52, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=52, bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn2 = nn.BatchNorm2d(52, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv3 = nn.Conv2d(52, 20, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn3 = nn.BatchNorm2d(20, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv1 = nn.Conv2d(20, 135, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn1 = nn.BatchNorm2d(135, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv2 = nn.Conv2d(135, 135, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=135, bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn2 = nn.BatchNorm2d(135, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv3 = nn.Conv2d(135, 20, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn3 = nn.BatchNorm2d(20, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv1 = nn.Conv2d(20, 114, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn1 = nn.BatchNorm2d(114, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv2 = nn.Conv2d(114, 114, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=114, bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn2 = nn.BatchNorm2d(114, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv3 = nn.Conv2d(114, 20, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn3 = nn.BatchNorm2d(20, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv1 = nn.Conv2d(20, 120, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn1 = nn.BatchNorm2d(120, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv2 = nn.Conv2d(120, 120, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=120, bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn2 = nn.BatchNorm2d(120, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv3 = nn.Conv2d(120, 20, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn3 = nn.BatchNorm2d(20, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv1 = nn.Conv2d(20, 100, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn1 = nn.BatchNorm2d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv2 = nn.Conv2d(100, 100, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=100, bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn2 = nn.BatchNorm2d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv3 = nn.Conv2d(100, 29, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn3 = nn.BatchNorm2d(29, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv1 = nn.Conv2d(29, 200, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn1 = nn.BatchNorm2d(200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv2 = nn.Conv2d(200, 200, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=200, bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn2 = nn.BatchNorm2d(200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv3 = nn.Conv2d(200, 29, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn3 = nn.BatchNorm2d(29, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv1 = nn.Conv2d(29, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn1 = nn.BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv2 = nn.Conv2d(192, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=192, bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn2 = nn.BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv3 = nn.Conv2d(192, 29, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn3 = nn.BatchNorm2d(29, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv1 = nn.Conv2d(29, 206, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn1 = nn.BatchNorm2d(206, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv2 = nn.Conv2d(206, 206, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=206, bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn2 = nn.BatchNorm2d(206, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv3 = nn.Conv2d(206, 49, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn3 = nn.BatchNorm2d(49, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv1 = nn.Conv2d(49, 318, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn1 = nn.BatchNorm2d(318, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv2 = nn.Conv2d(318, 318, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=318, bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn2 = nn.BatchNorm2d(318, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv3 = nn.Conv2d(318, 49, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn3 = nn.BatchNorm2d(49, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv1 = nn.Conv2d(49, 339, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn1 = nn.BatchNorm2d(339, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv2 = nn.Conv2d(339, 339, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=339, bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn2 = nn.BatchNorm2d(339, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv3 = nn.Conv2d(339, 49, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn3 = nn.BatchNorm2d(49, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv1 = nn.Conv2d(49, 314, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn1 = nn.BatchNorm2d(314, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv2 = nn.Conv2d(314, 314, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=314, bias=False)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn2 = nn.BatchNorm2d(314, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv3 = nn.Conv2d(314, 175, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn3 = nn.BatchNorm2d(175, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.conv_last = nn.Conv2d(175, 714, kernel_size=(1, 1), stride=(1, 1), bias=False)
        self.bn_last = nn.BatchNorm2d(714, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.avgpool = nn.AdaptiveAvgPool2d(output_size=1)
        self.fc = nn.Linear(in_features=714, out_features=1000, bias=True)

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_0_LinearBottleneck0_0_bn3(x)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_0_bn3(x)
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_1_LinearBottleneck1_1_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_0_bn3(x)
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_1_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_2_LinearBottleneck2_2_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_0_bn3(x)
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_1_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_2_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_3_LinearBottleneck3_3_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_0_bn3(x)
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_1_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_4_LinearBottleneck4_2_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_0_bn3(x)
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_1_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x_main = x
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv1(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn1(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv2(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn2(x_main)
        x_main = F.relu6(x_main, inplace=True)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_conv3(x_main)
        x_main = self.bottlenecks_Bottlenecks_5_LinearBottleneck5_2_bn3(x_main)
        x_residual = x
        x = x_main + x_residual
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv1(x)
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn1(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv2(x)
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn2(x)
        x = F.relu6(x, inplace=True)
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_conv3(x)
        x = self.bottlenecks_Bottlenecks_6_LinearBottleneck6_0_bn3(x)
        x = self.conv_last(x)
        x = self.bn_last(x)
        x = F.relu6(x, inplace=True)
        x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

def mobilenetv2(**kwargs):
    return MobileNetV2(**kwargs)
